site_name: bitterbake Documentation
site_url: https://gauravagarwalgarg.github.io/bitterbake/docs
repo_url: https://github.com/gauravagarwalgarg/bitterbake
theme:
  name: material
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Architecture: architecture.md
  - End-to-End CVE Process: cve-process.md
